# This is a basic workflow to help you get started with Actions

name: 构建镜像并push到镜像仓库

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: # job的一系列动作
      # 切换分支获取源码
      - name: Checkout # step的名称，将会在 github action 的控制台中显示
        # 选择一个action，可以理解为若干 steps.run，有利于代码复用
        uses: actions/checkout@master
      # 安装使用 node:10.21.0
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      # 运行命令，npm install && npm run build
      - name: npm install and build
        run: |
          npm install
          npm run docs:build
        env:
          CI: true

      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"
      - name: Build and push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t registry.cn-hangzhou.aliyuncs.com/yunfei_project/blog_image:$IMAGE_TAG .
          docker push registry.cn-hangzhou.aliyuncs.com/yunfei_project/blog_image:$IMAGE_TAG
